# Generated by Django 4.2 on 2025-03-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"permissions": [("can_manage_mailings", "Can manage mailings")]},
        ),
    ]
